{% set name = "docstring_parser" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cde5fbf8b846433dfbde1e0f96b7f909336a634d5df34a38cb75050c7346734a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - docstring_parser

about:
  home: https://github.com/rr-/docstring_parser
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Parse Python docstrings in reST and Google format '
  description: |
    Parse Python docstrings. Currently support ReST, Google, and Numpydoc-style
    docstrings.
  dev_url: https://github.com/rr-/docstring_parser

extra:
  recipe-maintainers:
    - Chilipp
    - rr-
