{% set name = "docstring_parser" %}
{% set version = "0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 538beabd0af1e2db0146b6bd3caa526c35a34d61af9fd2887f3a8a27a739aa6e

build:
  skip: True  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - poetry-core >=1.0.0
    - pip
  run:
    - python

test:
  source_files:
    - docstring_parser
  imports:
    - docstring_parser
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v docstring_parser

about:
  home: https://github.com/rr-/docstring_parser
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Parse Python docstrings in reST and Google format '
  description: |
    Parse Python docstrings. Currently support ReST, Google, and Numpydoc-style
    docstrings.
  dev_url: https://github.com/rr-/docstring_parser
  doc_url: https://github.com/rr-/docstring_parser

extra:
  recipe-maintainers:
    - Chilipp
    - rr-
